## 用pennylane來實踐跟qiskit一樣的架構

In [1]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.templates import BasicEntanglerLayers

In [2]:
dev = qml.device('qulacs.simulator', wires=2)

In [2]:
#控制上下左右走的unitary，有兩種
Unitary_Matrix_1 = np.array([[0,0,0,1],
                             [1,0,0,0],
                             [0,1,0,0],
                             [0,0,1,0]])

Unitary_Matrix_2 = np.array([[0,1,0,0],
                             [0,0,1,0],
                             [0,0,0,1],
                             [1,0,0,0]])


Go_Down = Unitary_Matrix_1
Go_Right = Unitary_Matrix_1
Go_Up = Unitary_Matrix_2
Go_Left = Unitary_Matrix_2


In [3]:
#控制end status如何變化的unitary，有兩種
end_status_1 = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                         [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0]])

end_status_2 = np.array([[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                         [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])


'''
end_status_1是踩到洞的時候會apply在end_status qubit上的unitary 
end_status_2是踩到終點的時候會apply在end_status qubit上的unitary
'''

'\nend_status_1是踩到洞的時候會apply在end_status qubit上的unitary \nend_status_2是踩到終點的時候會apply在end_status qubit上的unitary\n'

In [4]:
#控制reward如何變化的unitary，有三種
reward_unitary = np.array([[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                           [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

punish_unitary = np.array([[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                           [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]])

goal_unitary = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                         [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                         [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0]])

'''
reward_unitary:沒有踩到洞也沒有踩到終點的時候作用，會對reward減一
punish_unitray:踩到洞的時候作用，對reward減四
goal_unitary:踩到終點的時候作用，對reward加一 
'''

'\nreward_unitary:沒有踩到洞也沒有踩到終點的時候作用，會對reward減一\npunish_unitray:踩到洞的時候作用，對reward減四\ngoal_unitary:踩到終點的時候作用，對reward加一 \n'

## 選哪個動作是和環境independent的，四方向equally superposition

In [19]:
#創建quantum circuit
dev = qml.device('default.qubit', wires = 22, shots = 10)

#'environment_0','environment_1','environment_2','environment_3','first action_0',
                  #first_action_1','second_action_0','second_action_1','third_action_0','third_action1',
                  #fourth_action_0','fourth_action_1','fifth_action_0','fifth_action_1','status_0',
                   #status_1','status_2','status_3','reward_0','reward_1','reward_2','reward3'
#對應的qubit作用0~22
            
@qml.qnode(dev)
def circuit():
    #使每一個action選擇都是equally superposition
    for i in range(10):
        qml.Hadamard(i+4)
    #使reward一開始是最大的狀態
    for j in range(4):
        qml.PauliX(j+18)
    #控制上下左右
    for k in range(2):
        qml.ControlledQubitUnitary(Go_Right, control_wires = [2*k+4,2*k+5,14,15,16,17], wires = [2,3], control_values='000000')
        qml.ControlledQubitUnitary(Go_Left, control_wires = [2*k+4,2*k+5,14,15,16,17], wires = [2,3], control_values='100000')
        qml.ControlledQubitUnitary(Go_Up, control_wires = [2*k+4,2*k+5,14,15,16,17], wires = [0,1], control_values='010000')
        qml.ControlledQubitUnitary(Go_Down, control_wires = [2*k+4,2*k+5,14,15,16,17], wires = [0,1], control_values='110000')
        #判斷踩到什麼東西去判斷怎麼操作end_status
        #Part 1:踩到洞
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [14,15,16,17], control_values='0101')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [14,15,16,17], control_values='0111')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [14,15,16,17], control_values='1011')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [14,15,16,17], control_values='1100')
        #Part 2:踩到終點
        qml.ControlledQubitUnitary(end_status_2, control_wires = [0,1,2,3], wires = [14,15,16,17], control_values='1010')

        #由end_status qubits去判斷reward要怎麼動作
        #Part 1:什麼東西都沒踩到過
        qml.ControlledQubitUnitary(reward_unitary, control_wires = [14,15,16,17], wires = [18,19,20,21], control_values='0000')
        #Part 2:第一次踩到洞
        qml.ControlledQubitUnitary(punish_unitary, control_wires = [14,15,16,17], wires = [18,19,20,21], control_values='0001')
        #Part 3:第一次踩到終點
        qml.ControlledQubitUnitary(goal_unitary, control_wires = [14,15,16,17], wires = [18,19,20,21], control_values='1111')
    
    return [qml.sample(qml.PauliZ(i)) for i in range(22)]

In [20]:
drawer = qml.draw(circuit)
print(drawer())

  0: ───────────────╭U1──╭U0──╭C───╭C───╭C───╭C───╭C────────────────────────────╭U1──╭U0──╭C───╭C───╭C───╭C───╭C──────────────────┤ Sample[Z] 
  1: ───────────────├U1──├U0──├C───├C───├C───├C───├C────────────────────────────├U1──├U0──├C───├C───├C───├C───├C──────────────────┤ Sample[Z] 
  2: ─────╭U0──╭U1──│────│────├C───├C───├C───├C───├C──────────────────╭U0──╭U1──│────│────├C───├C───├C───├C───├C──────────────────┤ Sample[Z] 
  3: ─────├U0──├U1──│────│────├C───├C───├C───├C───├C──────────────────├U0──├U1──│────│────├C───├C───├C───├C───├C──────────────────┤ Sample[Z] 
  4: ──H──├C───├C───├C───├C───│────│────│────│────│───────────────────│────│────│────│────│────│────│────│────│───────────────────┤ Sample[Z] 
  5: ──H──├C───├C───├C───├C───│────│────│────│────│───────────────────│────│────│────│────│────│────│────│────│───────────────────┤ Sample[Z] 
  6: ──H──│────│────│────│────│────│────│────│────│───────────────────├C───├C───├C───├C───│────│────│────│────│───────────────────┤ Sample[Z] 

In [50]:
A = circuit()
A

array([[ 1,  1,  1, -1, -1, -1, -1,  1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1,  1, -1,  1],
       [-1,  1, -1,  1,  1,  1,  1, -1,  1,  1],
       [ 1,  1,  1, -1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1,  1,  1,  1,  1,  1,  1, -1],
       [ 1,  1,  1,  1, -1, -1, -1,  1, -1, -1],
       [ 1,  1,  1, -1, -1,  1,  1,  1, -1, -1],
       [-1,  1, -1,  1, -1, -1, -1,  1, -1,  1],
       [ 1, -1, -1, -1, -1,  1,  1, -1,  1,  1],
       [ 1, -1,  1,  1,  1,  1,  1,  1,  1, -1],
       [ 1,  1,  1,  1,  1, -1,  1,  1, -1,  1],
       [-1,  1, -1,  1,  1,  1, -1, -1,  1,  1],
       [ 1,  1,  1,  1, -1, -1,  1, -1, -1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1, -1, -1, -1,  1, -1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1,  1,  1,  1, -1,  1, -1],
       [ 1,  1,  1, 

In [52]:
B = np.where(A==1,0,1)
B

tensor([[0, 0, 0, 1, 1, 1, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 1, 1, 0, 1, 0],
        [1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0, 0, 0, 1, 1],
        [1, 0, 1, 0, 1, 1, 1, 0, 1, 0],
        [0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
        [1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 1, 1, 1],
        [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], requires_grad=True)

## 決定走哪個方向是depend on現在在哪個state，會經過QNN吐出決定的動作(用來驗證路徑正確性，因為qml.sample不能微分)

In [42]:
#創建quantum circuit
num_of_repeat = 3
dev = qml.device('default.qubit', wires = 12+num_of_repeat*4, shots = 20)
shape = BasicEntanglerLayers.shape(n_layers=1, n_wires=4)
initial_weights = np.random.random(size=shape)*np.pi
@qml.qnode(dev)
def circuit(weights):
    #使reward一開始是最大的狀態
    for j in range(4):
        qml.PauliX(j+((num_of_repeat*4)+8))
    #控制上下左右
    for k in range(num_of_repeat):
        qml.CNOT(wires=[0,4*k+4])
        qml.CNOT(wires=[1,4*k+5])
        qml.CNOT(wires=[2,4*k+6])
        qml.CNOT(wires=[3,4*k+7])
        BasicEntanglerLayers(weights=weights, wires=[4*k+4,4*k+5,4*k+6,4*k+7])
        qml.ControlledQubitUnitary(Go_Right, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [2,3], control_values='000000')
        qml.ControlledQubitUnitary(Go_Left, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [2,3], control_values='100000')
        qml.ControlledQubitUnitary(Go_Up, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [0,1], control_values='010000')
        qml.ControlledQubitUnitary(Go_Down, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [0,1], control_values='110000')

        #判斷踩到什麼東西去判斷怎麼操作end_status
        #Part 1:踩到洞
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='0101')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='0111')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='1011')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='1100')
        #Part 2:踩到終點
        qml.ControlledQubitUnitary(end_status_2, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='0010')

        #由end_status qubits去判斷reward要怎麼動作
        #Part 1:什麼東西都沒踩到過
        qml.ControlledQubitUnitary(reward_unitary, control_wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [4*num_of_repeat+8,4*num_of_repeat+9,4*num_of_repeat+10,4*num_of_repeat+11], control_values='0000')
        #Part 2:第一次踩到洞
        qml.ControlledQubitUnitary(punish_unitary, control_wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [4*num_of_repeat+8,4*num_of_repeat+9,4*num_of_repeat+10,4*num_of_repeat+11], control_values='0001')
        #Part 3:第一次踩到終點
        qml.ControlledQubitUnitary(goal_unitary, control_wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [4*num_of_repeat+8,4*num_of_repeat+9,4*num_of_repeat+10,4*num_of_repeat+11], control_values='1111')
    return [qml.sample(qml.PauliZ(i)) for i in range(num_of_repeat*4+12)]


In [27]:
drawer = qml.draw(circuit)
print(drawer(initial_weights))

  0: ──────────────╭C──────────────────────────────────────╭U1──╭U0──╭C───╭C───╭C───╭C───╭C──────────────────┤ Sample[Z] 
  1: ──────────╭C──│───────────────────────────────────────├U1──├U0──├C───├C───├C───├C───├C──────────────────┤ Sample[Z] 
  2: ──────╭C──│───│─────────────────────────────╭U0──╭U1──│────│────├C───├C───├C───├C───├C──────────────────┤ Sample[Z] 
  3: ──╭C──│───│───│─────────────────────────────├U0──├U1──│────│────├C───├C───├C───├C───├C──────────────────┤ Sample[Z] 
  4: ──│───│───│───╰X──RX(2.62)──╭C──────────╭X──├C───├C───├C───├C───│────│────│────│────│───────────────────┤ Sample[Z] 
  5: ──│───│───╰X──────RX(1.56)──╰X──╭C──────│───├C───├C───├C───├C───│────│────│────│────│───────────────────┤ Sample[Z] 
  6: ──│───╰X──────────RX(1.64)──────╰X──╭C──│───│────│────│────│────│────│────│────│────│───────────────────┤ Sample[Z] 
  7: ──╰X──────────────RX(2.58)──────────╰X──╰C──│────│────│────│────│────│────│────│────│───────────────────┤ Sample[Z] 
  8: ───────────────────

In [43]:
def cost(params):
    result = []
    x = circuit(params)
    y = np.where(x==1,0,1)
    y1 = y[0:6,:]
    y2 = y[8:10,:]
    y3 = y[12:14,:]
    y4 = y[16:24,:]
    #x4 = x[16:18]
    #x5 = x[20:22]
    X = np.concatenate((y1,y2),axis=0)
    Y = np.concatenate((y3,y4),axis=0)
    result = np.concatenate((X,Y),axis=0)
    reward_part = result[14:18,:]
    total_reward = np.sum(reward_part[0,:])*8 + np.sum(reward_part[1,:]*4) + np.sum(reward_part[2,:]*2) + np.sum(reward_part[3,:])
    average_reward = total_reward/reward_part.shape[1]
    print(result)
    print(average_reward)
    return average_reward

cost(weights)

[[1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0]
 [1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 0]
 [1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 1 0]
 [0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1]
 [0 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 1 1]
 [0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0]]
11.25


tensor(11.25, requires_grad=True)

## 決定走哪個方向是depend on現在在哪個state，會經過QNN吐出決定的動作(使用qml.expval)

In [5]:
#創建quantum circuit
num_of_repeat = 3
dev = qml.device('default.qubit', wires = 12+num_of_repeat*4)
shape = BasicEntanglerLayers.shape(n_layers=1, n_wires=4)
initial_weights = np.random.random(size=shape)*np.pi
@qml.qnode(dev)
def circuit(weights):
    #使reward一開始是最大的狀態
    for j in range(4):
        qml.PauliX(j+((num_of_repeat*4)+8))
    #控制上下左右
    for k in range(num_of_repeat):
        qml.CNOT(wires=[0,4*k+4])
        qml.CNOT(wires=[1,4*k+5])
        qml.CNOT(wires=[2,4*k+6])
        qml.CNOT(wires=[3,4*k+7])
        BasicEntanglerLayers(weights=weights, wires=[4*k+4,4*k+5,4*k+6,4*k+7])
        qml.ControlledQubitUnitary(Go_Right, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [2,3], control_values='000000')
        qml.ControlledQubitUnitary(Go_Left, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [2,3], control_values='100000')
        qml.ControlledQubitUnitary(Go_Up, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [0,1], control_values='010000')
        qml.ControlledQubitUnitary(Go_Down, control_wires = [4*k+4,4*k+5,4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [0,1], control_values='110000')

        #判斷踩到什麼東西去判斷怎麼操作end_status
        #Part 1:踩到洞
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='0101')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='0111')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='1011')
        qml.ControlledQubitUnitary(end_status_1, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='1100')
        #Part 2:踩到終點
        qml.ControlledQubitUnitary(end_status_2, control_wires = [0,1,2,3], wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], control_values='0110')

        #由end_status qubits去判斷reward要怎麼動作
        #Part 1:什麼東西都沒踩到過
        qml.ControlledQubitUnitary(reward_unitary, control_wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [4*num_of_repeat+8,4*num_of_repeat+9,4*num_of_repeat+10,4*num_of_repeat+11], control_values='0000')
        #Part 2:第一次踩到洞
        qml.ControlledQubitUnitary(punish_unitary, control_wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [4*num_of_repeat+8,4*num_of_repeat+9,4*num_of_repeat+10,4*num_of_repeat+11], control_values='0001')
        #Part 3:第一次踩到終點
        qml.ControlledQubitUnitary(goal_unitary, control_wires = [4*num_of_repeat+4,4*num_of_repeat+5,4*num_of_repeat+6,4*num_of_repeat+7], wires = [4*num_of_repeat+8,4*num_of_repeat+9,4*num_of_repeat+10,4*num_of_repeat+11], control_values='1111')
    return [qml.expval(qml.PauliZ(i)) for i in range(num_of_repeat*4+12)]

In [6]:
def cost(params):
    y = circuit(params)
    #y = np.where(x==1,0,1)
    y1 = y[20:24]
    print(y1)
    total_reward = y1[0]*8 + y1[1]*4 + y1[2]*2 + y1[3]
    return total_reward

cost(initial_weights)

[-1.         -0.97241912  0.97251468  0.98033209]


tensor(-8.96431505, requires_grad=True)

In [7]:
opt = qml.AdamOptimizer(stepsize=0.2)
steps = 100
weights = initial_weights
for i in range(steps):
    weights = opt.step(cost, weights)
    #print("Now angles: {}".format(weights))
    
    if (i + 1) % 5 == 0:
        print("Cost after step {:5d}: {: .7f}".format(i + 1, cost(weights)))

print("Optimized rotation angles: {}".format(weights))

Autograd ArrayBox with value [-1.         -0.97241912  0.97251468  0.98033209]
Autograd ArrayBox with value [-1.         -0.99375154  0.99383189  0.99644654]
Autograd ArrayBox with value [-1.         -0.94591628  0.94688926  0.96539337]
Autograd ArrayBox with value [-1.         -0.89371324  0.89622826  0.93034607]
Autograd ArrayBox with value [-1.         -0.86079163  0.86350617  0.90721007]
[-1.         -0.85128602  0.85379767  0.89881358]
Cost after step     5: -8.7987352
Autograd ArrayBox with value [-1.         -0.85128602  0.85379767  0.89881358]
Autograd ArrayBox with value [-1.         -0.86206229  0.86428724  0.90382746]
Autograd ArrayBox with value [-1.         -0.88719471  0.88884659  0.9190533 ]
Autograd ArrayBox with value [-1.         -0.91946627  0.92041442  0.94009297]
Autograd ArrayBox with value [-1.         -0.9516517   0.95203886  0.96221849]
[-1.         -0.97771485  0.97780733  0.98120959]
Cost after step    10: -8.9740352
Autograd ArrayBox with value [-1.         

KeyboardInterrupt: 

In [24]:
shape = BasicEntanglerLayers.shape(n_layers=1, n_wires=4)
weights = np.random.random(size=shape)
drawer = qml.draw(circuit)
print(drawer(weights))

  0: ───────────────╭C────────────────────────────────────────────╭U4──╭U3──╭C───╭C───╭C───╭C───╭C───────────────╭C───────────────────────────────────────╭U4──╭U3──╭C───╭C───╭C───╭C───╭C───────────────╭C───────────────────────────────────────╭U4──╭U3───────╭C────────╭C────────╭C────────╭C────────╭C────────────────────╭C──────────────────────────────────────────────────────╭U4──╭U3──╭C───╭C───╭C───╭C───╭C───────────────╭C───────────────────────────────────────╭U4──╭U3──╭C───╭C───╭C───╭C───╭C───┤ Sample[Z] 
  1: ───────────╭C──│─────────────────────────────────────────────├U4──├U3──├C───├C───├C───├C───├C───────────╭C──│────────────────────────────────────────├U4──├U3──├C───├C───├C───├C───├C───────────╭C──│────────────────────────────────────────├U4──├U3───────├C────────├C────────├C────────├C────────├C────────────────╭C──│───────────────────────────────────────────────────────├U4──├U3──├C───├C───├C───├C───├C───────────╭C──│────────────────────────────────────────├U4──├U3──├C───├C───├C───├