In [101]:
import pennylane as qml
from pennylane.templates import BasicEntanglerLayers
from pennylane import numpy as np

In [50]:
n_wires = 3
dev = qml.device('default.qubit', wires=n_wires)

@qml.qnode(dev)
def circuit(weights):
    BasicEntanglerLayers(weights=weights, wires=[0,1,2]) #原本是wires=range(3)
    return qml.expval(qml.PauliZ(0))

shape = BasicEntanglerLayers.shape(n_layers=2, n_wires=n_wires)
np.random.seed(42)  # to make the result reproducable
weights = np.random.random(size=shape)

In [51]:
circuit(weights)

tensor(0.72588592, requires_grad=True)

In [56]:
drawer = qml.draw(circuit(weights))
print(drawer(weights))

AttributeError: 'tensor' object has no attribute 'construct'

In [19]:
A = range(3))

In [7]:
print(A)

range(0, 3)


In [148]:
dev2 = qml.device('default.qubit', wires=6)
U = np.array([[0, 0, 0, 1],
              [1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0]])
@qml.qnode(dev2)
def circuit(weights):
    qml.ControlledQubitUnitary(U, control_wires = [0, 1], wires = [2, 3])
    BasicEntanglerLayers(weights=weights, wires=[0,1,2,3])
    return [qml.expval(qml.PauliZ(i)) for i in range(4)]
def cost(params):
    A = circuit(params)[0:2]
    B = circuit(params)[3]
    C = circuit(params)[2]
    result = np.append(np.append(A,B),C)
    print(A)
    print(B)
    print(result)
    return np.sum(A)
shape = BasicEntanglerLayers.shape(n_layers=2, n_wires=4)
weights = np.random.random(size=shape)
print(cost(weights))

[0.30094386 0.55761141]
0.4331721263553286
[0.30094386 0.55761141 0.43317213 0.61006115]
0.8585552748405385


In [125]:
opt = qml.GradientDescentOptimizer(stepsize=0.01)
steps = 100
for i in range(steps):
    #更新U3 GATE的參數
    weights = opt.step(cost, weights)

    if (i + 1) % 5 == 0:
        print("Cost after step {:5d}: {: .7f}".format(i + 1, cost(weights)))

print("Optimized rotation angles: {}".format(params))

Autograd ArrayBox with value [0.38171519 0.32927399]
Autograd ArrayBox with value [0.3784911  0.32584322]
Autograd ArrayBox with value [0.37521972 0.3224072 ]
Autograd ArrayBox with value [0.37190025 0.3189657 ]
Autograd ArrayBox with value [0.3685319 0.3155185]
[0.36511392 0.31206541]
Cost after step     5:  0.6771793
Autograd ArrayBox with value [0.36511392 0.31206541]
Autograd ArrayBox with value [0.36164555 0.30860624]
Autograd ArrayBox with value [0.35812608 0.30514081]
Autograd ArrayBox with value [0.3545548  0.30166895]
Autograd ArrayBox with value [0.35093104 0.29819052]
[0.34725415 0.29470535]
Cost after step    10:  0.6419595
Autograd ArrayBox with value [0.34725415 0.29470535]
Autograd ArrayBox with value [0.34352349 0.29121334]
Autograd ArrayBox with value [0.33973849 0.28771436]
Autograd ArrayBox with value [0.33589855 0.28420831]
Autograd ArrayBox with value [0.33200314 0.2806951 ]
[0.32805176 0.27717465]
Cost after step    15:  0.6052264
Autograd ArrayBox with value [0.3

In [117]:
drawer = qml.draw(circuit)
print(drawer(weights))

 0: ──╭C───RX(0.238)──╭C──────────────────────────────╭X──RX(0.634)──╭C──────────╭X──┤ ⟨Z⟩ 
 1: ──├C───RX(0.728)──╰X──╭C───RX(0.536)──────────────│──────────────╰X──╭C──────│───┤ ⟨Z⟩ 
 2: ──├U0──RX(0.368)──────╰X──╭C──────────RX(0.0903)──│──────────────────╰X──╭C──│───┤     
 3: ──╰U0──RX(0.632)──────────╰X──────────────────────╰C──RX(0.835)──────────╰X──╰C──┤     
U0 =
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]



In [79]:
dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit(a, w):
    qml.Hadamard(0)
    qml.CRX(a, wires=[0, 1])
    qml.Rot(*w, wires=[1])
    qml.CRX(-a, wires=[0, 1])
    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1))

In [80]:
drawer = qml.draw(circuit)

In [81]:
print(drawer(a=2.3, w=[1.2, 3.2, 0.7]))

 0: ──H──╭C────────────────────────────╭C─────────╭┤ ⟨Z ⊗ Z⟩ 
 1: ─────╰RX(2.3)──Rot(1.2, 3.2, 0.7)──╰RX(-2.3)──╰┤ ⟨Z ⊗ Z⟩ 



In [149]:
A = np.zeros((2,5))

In [155]:
A

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)